---
abstract: 'Parser for Apache Log (common, combined, and any other custom styles by LogFormat).'
author:
  - 'TAGOMORI Satoshi <tagomoris at gmail.com>'
build_requires:
  Test::Deep: 0
  Test::More: 0.98
configure_requires:
  CPAN::Meta: 0
  CPAN::Meta::Prereqs: 0
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Minilla/v0.6.6, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Apache-Log-Parser
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
provides:
  Apache::Log::Parser:
    file: lib/Apache/Log/Parser.pm
    version: 0.01
requires:
  perl: 5.008001
resources:
  bugtracker: https://github.com/tagomoris/Apache-Log-Parser/issues
  homepage: https://github.com/tagomoris/Apache-Log-Parser
  repository: git://github.com/tagomoris/Apache-Log-Parser.git
version: 0.01
x_contributors:
  - 'TAGOMORI Satoshi <tagomoris@livedoor.jp>'
  - 'TAGOMORI Satoshi <tagomoris@gmail.com>'
